# Chart API 버전 (Helm 3는 v2 사용)
apiVersion: v2

# Chart 이름 - helm install 시 참조되는 이름
name: ml-server-chart

# Chart 설명 - helm search 시 표시됨
description: A Helm chart for ML Model Server

# Chart 타입
# application → 일반 애플리케이션 Chart
# library → 재사용 가능한 템플릿 라이브러리
type: application

# Chart 버전 - Chart 자체의 버전 (의미적 버전 사용 권장)
version: 0.1.0

# 애플리케이션 버전 - 배포되는 애플리케이션의 버전
appVersion: "1.0.0"
